---
- hosts: servers
  name: Server Base Config

  pre_tasks:
    - name: update yum packages to latest
      yum: name='*' state=latest

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.ntp
    - geerlingguy.docker
    - geerlingguy.clamav
  tasks:
